### ISSUE TITLE
TV Series Search Results Content Selection

### ISSUE THREAD

**Issue by yashtibrewal** [yashtibrewal/entertainment-app-frontend#15]
Normally when we click on a card, it opens the details for that content.

For Searched results on the TV-Series page this feature doesn't work.

![image](https://github.com/user-attachments/assets/58dfd825-0506-4784-82f3-e78128cda7de)

Expected: Should work.

**Comment by Nitish814112** [comment]
closed in 710b8e0f225f9b9bcc008ecc2e76480118d5e19c
