### ISSUE TITLE
Searched Content does not show all details

### ISSUE THREAD

**Issue by yashtibrewal** [yashtibrewal/entertainment-app-frontend#17]
![image](https://github.com/user-attachments/assets/1515cca4-2880-481d-92f6-fac5f15fe81f)

It should show the details which are normally seen on a normal page.

Like these.
![image](https://github.com/user-attachments/assets/c7efbfab-da92-4faf-8406-12042914f49d)

**Comment by Nitish814112** [comment]
duplicate #49
